"""Generated docs repository for CRUD operations on the generated_docs table."""

import json
from datetime import datetime
from typing import Any
from uuid import UUID

from ..database import DatabaseManager
from ..logging import get_logger
from ..models import GeneratedDocRecord

logger = get_logger(__name__)


class GeneratedDocsRepository:
    """Repository for tracking generated and delivered documents."""

    def __init__(self, db: DatabaseManager):
        """Initialize generated docs repository.

        Args:
            db: DatabaseManager instance for database operations.
        """
        self._db = db

    async def create(
        self,
        doc_id: UUID | str,
        tool_name: str,
        caller: str,
        target_path: str,
        content_hash: str,
        size_bytes: int,
        trace_id: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> str:
        """Create a new generated doc record.

        Args:
            doc_id: Unique document identifier (UUID or string).
            tool_name: Name of the tool that generated this document.
            caller: Caller identifier.
            target_path: Path where the document was written.
            content_hash: SHA256 hash of document content.
            size_bytes: Document size in bytes.
            trace_id: Optional trace ID for request tracking.
            metadata: Optional metadata dictionary.

        Returns:
            The doc_id as a string.
        """
        now = datetime.utcnow().isoformat()
        doc_id_str = str(doc_id)
        meta_json = json.dumps(metadata or {})

        await self._db.execute(
            """INSERT INTO generated_docs (doc_id, trace_id, tool_name, caller, target_path, content_hash, size_bytes, metadata, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                doc_id_str,
                trace_id,
                tool_name,
                caller,
                target_path,
                content_hash,
                size_bytes,
                meta_json,
                now,
            ),
        )
        logger.info(
            "generated_doc_created",
            doc_id=doc_id_str,
            tool_name=tool_name,
            target_path=target_path,
        )
        return doc_id_str

    async def get(self, doc_id: str | UUID) -> GeneratedDocRecord | None:
        """Get a document by ID.

        Args:
            doc_id: Unique document identifier.

        Returns:
            GeneratedDocRecord instance if found, None otherwise.
        """
        doc_id_str = str(doc_id)
        row = await self._db.fetchone(
            "SELECT * FROM generated_docs WHERE doc_id = ?", (doc_id_str,)
        )
        if not row:
            return None
        return self._row_to_record(row)

    async def list_all(self, limit: int = 100) -> list[GeneratedDocRecord]:
        """List all generated documents.

        Args:
            limit: Maximum number of records to return.

        Returns:
            List of GeneratedDocRecord instances ordered by creation date (newest first).
        """
        rows = await self._db.fetchall(
            "SELECT * FROM generated_docs ORDER BY created_at DESC LIMIT ?", (limit,)
        )
        return [self._row_to_record(row) for row in rows]

    async def list_by_trace(self, trace_id: str) -> list[GeneratedDocRecord]:
        """Get all documents with a specific trace ID.

        Args:
            trace_id: Trace identifier to search by.

        Returns:
            List of GeneratedDocRecord instances with the specified trace ID.
        """
        rows = await self._db.fetchall(
            "SELECT * FROM generated_docs WHERE trace_id = ? ORDER BY created_at DESC",
            (trace_id,),
        )
        return [self._row_to_record(row) for row in rows]

    async def list_by_tool(self, tool_name: str, limit: int = 100) -> list[GeneratedDocRecord]:
        """List all documents for a specific tool.

        Args:
            tool_name: Tool name to filter by.
            limit: Maximum number of records to return.

        Returns:
            List of GeneratedDocRecord instances for the specified tool.
        """
        rows = await self._db.fetchall(
            "SELECT * FROM generated_docs WHERE tool_name = ? ORDER BY created_at DESC LIMIT ?",
            (tool_name, limit),
        )
        return [self._row_to_record(row) for row in rows]

    async def list_by_caller(self, caller: str, limit: int = 100) -> list[GeneratedDocRecord]:
        """List all documents generated by a specific caller.

        Args:
            caller: Caller identifier to filter by.
            limit: Maximum number of records to return.

        Returns:
            List of GeneratedDocRecord instances for the specified caller.
        """
        rows = await self._db.fetchall(
            "SELECT * FROM generated_docs WHERE caller = ? ORDER BY created_at DESC LIMIT ?",
            (caller, limit),
        )
        return [self._row_to_record(row) for row in rows]

    async def delete(self, doc_id: str | UUID) -> bool:
        """Delete a document record.

        Args:
            doc_id: Unique document identifier.

        Returns:
            True if document was deleted, False if not found.
        """
        doc_id_str = str(doc_id)
        cursor = await self._db.execute(
            "DELETE FROM generated_docs WHERE doc_id = ?", (doc_id_str,)
        )
        logger.info("generated_doc_deleted", doc_id=doc_id_str)
        return cursor.rowcount > 0

    async def count_by_tool(self) -> dict[str, int]:
        """Get count of documents grouped by tool.

        Returns:
            Dictionary mapping tool_name to count.
        """
        rows = await self._db.fetchall(
            "SELECT tool_name, COUNT(*) as count FROM generated_docs GROUP BY tool_name"
        )
        return {row["tool_name"]: row["count"] for row in rows}

    def _row_to_record(self, row) -> GeneratedDocRecord:
        """Convert database row to GeneratedDocRecord.

        Args:
            row: Database row from aiosqlite.

        Returns:
            GeneratedDocRecord instance.
        """
        metadata = json.loads(row["metadata"]) if row["metadata"] else {}

        return GeneratedDocRecord(
            doc_id=UUID(row["doc_id"]),
            trace_id=row["trace_id"],
            tool_name=row["tool_name"],
            caller=row["caller"],
            target_path=row["target_path"],
            content_hash=row["content_hash"],
            size_bytes=row["size_bytes"],
            created_at=datetime.fromisoformat(row["created_at"]),
            metadata=metadata,
        )
